"""init

Revision ID: 30cf64d7030a
Revises: 
Create Date: 2026-05-28 14:14:19.947717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30cf64d7030a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filament_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('printer_model', sa.String(length=100), nullable=False, comment='Модель принтера'),
    sa.Column('printer_nozzle_diameter', sa.Float(), nullable=False, comment='Диаметр сопла в мм'),
    sa.Column('filament_brand', sa.String(length=100), nullable=False, comment='Бренд пластика'),
    sa.Column('filament_type', sa.String(length=50), nullable=False, comment='Тип пластика'),
    sa.Column('filament_diameter', sa.Float(), nullable=False, comment='Диаметр прутка в мм'),
    sa.Column('chamber_temp', sa.Integer(), nullable=False, comment='Температура термокамеры 0–100°C'),
    sa.Column('nozzle_temp_first_layer', sa.Integer(), nullable=False, comment='Температура сопла для первого слоя'),
    sa.Column('nozzle_temp_other_layers', sa.Integer(), nullable=False, comment='Температура сопла для остальных слоёв'),
    sa.Column('bed_temp_first_layer', sa.Integer(), nullable=False, comment='Температура стола первый слой'),
    sa.Column('bed_temp_other_layers', sa.Integer(), nullable=False, comment='Температура стола остальные слои'),
    sa.Column('bed_temp_initial', sa.Integer(), nullable=False, comment='Начальная температура стола (для градиентного нагрева)'),
    sa.Column('bed_temp_final', sa.Integer(), nullable=False, comment='Финальная температура стола'),
    sa.Column('fan_min_speed', sa.Integer(), nullable=False, comment='Мин. скорость вентилятора (%)'),
    sa.Column('fan_min_layer_time', sa.Integer(), nullable=False, comment='Время слоя (сек) для мин. скорости вентилятора'),
    sa.Column('fan_max_speed', sa.Integer(), nullable=False, comment='Макс. скорость вентилятора (%)'),
    sa.Column('fan_max_layer_time', sa.Integer(), nullable=False, comment='Время слоя (сек) для макс. скорости вентилятора'),
    sa.Column('fan_always_on', sa.Boolean(), nullable=False, comment='Вентилятор включен всегда'),
    sa.Column('slow_down_for_cooling', sa.Boolean(), nullable=False, comment='Замедлять печать для охлаждения'),
    sa.Column('retraction_distance', sa.Float(), nullable=False, comment='Длина отката в мм'),
    sa.Column('retraction_speed', sa.Float(), nullable=False, comment='Скорость отката в мм/с'),
    sa.Column('print_speed_first_layer', sa.Float(), nullable=False, comment='Скорость первого слоя в мм/с'),
    sa.Column('print_speed_other_layers', sa.Float(), nullable=False, comment='Скорость остальных слоёв в мм/с'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Сколько раз использовали этот профиль'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filament_settings_filament_type'), 'filament_settings', ['filament_type'], unique=False)
    op.create_index(op.f('ix_filament_settings_printer_model'), 'filament_settings', ['printer_model'], unique=False)
    op.drop_table('_dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_dummy',
    sa.Column('id', sa.INTEGER(), nullable=True)
    )
    op.drop_index(op.f('ix_filament_settings_printer_model'), table_name='filament_settings')
    op.drop_index(op.f('ix_filament_settings_filament_type'), table_name='filament_settings')
    op.drop_table('filament_settings')
    # ### end Alembic commands ###
