"""create printer_filament_profile and geometry_settings

Revision ID: 9bdbff72a108
Revises: c7575b2f4024
Create Date: 2026-05-28 15:29:28.222769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdbff72a108'
down_revision: Union[str, Sequence[str], None] = 'c7575b2f4024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geometry_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False, comment='Имя или хэш STL-модели'),
    sa.Column('min_layer_area', sa.Float(), nullable=False, comment='Минимальная площадь слоя (мм²)'),
    sa.Column('max_overhang_angle', sa.Float(), nullable=True, comment='Максимальный угол свеса в градусах'),
    sa.Column('has_bridges', sa.Boolean(), nullable=False, comment='Есть ли мосты'),
    sa.Column('min_wall_thickness', sa.Float(), nullable=True, comment='Минимальная толщина стенки (мм)'),
    sa.Column('max_height', sa.Float(), nullable=False, comment='Общая высота модели (мм)'),
    sa.Column('bounding_box_volume', sa.Float(), nullable=False, comment='Объём ограничивающего параллелепипеда (мм³)'),
    sa.Column('min_layer_time', sa.Float(), nullable=True, comment='Минимальное время слоя (сек)'),
    sa.Column('bridge_speed_multiplier', sa.Float(), nullable=False, comment='Множитель скорости на мостах'),
    sa.Column('bridge_fan_speed', sa.Integer(), nullable=True, comment='Скорость вентилятора на мостах (%)'),
    sa.Column('overhang_speed_multiplier', sa.Float(), nullable=False, comment='Множитель скорости для свесов'),
    sa.Column('support_angle_threshold', sa.Integer(), nullable=False, comment='Пороговый угол поддержек (градусы)'),
    sa.Column('enable_support', sa.Boolean(), nullable=False, comment='Генерировать поддержки'),
    sa.Column('support_type', sa.String(length=20), nullable=False, comment='Тип поддержек: normal, tree'),
    sa.Column('infill_percentage', sa.Integer(), nullable=False, comment='Процент заполнения'),
    sa.Column('infill_pattern', sa.String(length=30), nullable=False, comment='Паттерн заполнения'),
    sa.Column('wall_line_count', sa.Integer(), nullable=True, comment='Количество периметров'),
    sa.Column('top_layers', sa.Integer(), nullable=True, comment='Верхних сплошных слоёв'),
    sa.Column('bottom_layers', sa.Integer(), nullable=True, comment='Нижних сплошных слоёв'),
    sa.Column('brim_width', sa.Float(), nullable=True, comment='Ширина каймы (мм)'),
    sa.Column('raft_layers', sa.Integer(), nullable=True, comment='Количество слоёв raft'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('printer_filament_profile',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('printer_model', sa.String(length=100), nullable=False, comment='Модель принтера'),
    sa.Column('printer_nozzle_diameter', sa.Float(), nullable=False, comment='Диаметр сопла в мм'),
    sa.Column('filament_brand', sa.String(length=100), nullable=False, comment='Бренд пластика'),
    sa.Column('filament_type', sa.String(length=50), nullable=False, comment='Тип пластика'),
    sa.Column('chamber_temp', sa.Integer(), nullable=False, comment='Температура термокамеры 0–100°C'),
    sa.Column('nozzle_temp_first_layer', sa.Integer(), nullable=False, comment='Температура сопла для первого слоя'),
    sa.Column('nozzle_temp_other_layers', sa.Integer(), nullable=False, comment='Температура сопла для остальных слоёв'),
    sa.Column('bed_temp_first_layer', sa.Integer(), nullable=False, comment='Температура стола первый слой'),
    sa.Column('bed_temp_other_layers', sa.Integer(), nullable=False, comment='Температура стола остальные слои'),
    sa.Column('bed_temp_initial', sa.Integer(), nullable=False, comment='Начальная температура стола (для градиентного нагрева)'),
    sa.Column('bed_temp_final', sa.Integer(), nullable=False, comment='Финальная температура стола'),
    sa.Column('fan_min_speed', sa.Integer(), nullable=False, comment='Мин. скорость вентилятора (%)'),
    sa.Column('fan_min_layer_time', sa.Integer(), nullable=False, comment='Время слоя (сек) для мин. скорости вентилятора'),
    sa.Column('fan_max_speed', sa.Integer(), nullable=False, comment='Макс. скорость вентилятора (%)'),
    sa.Column('fan_max_layer_time', sa.Integer(), nullable=False, comment='Время слоя (сек) для макс. скорости вентилятора'),
    sa.Column('fan_always_on', sa.Boolean(), nullable=False, comment='Вентилятор включен всегда'),
    sa.Column('slow_down_for_cooling', sa.Boolean(), nullable=False, comment='Замедлять печать для охлаждения'),
    sa.Column('retraction_distance', sa.Float(), nullable=False, comment='Длина отката в мм'),
    sa.Column('retraction_speed', sa.Float(), nullable=False, comment='Скорость отката в мм/с'),
    sa.Column('print_speed_first_layer', sa.Float(), nullable=False, comment='Скорость первого слоя в мм/с'),
    sa.Column('print_speed_other_layers', sa.Float(), nullable=False, comment='Скорость остальных слоёв в мм/с'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Сколько раз использовали этот профиль'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_filament_profile_filament_type'), 'printer_filament_profile', ['filament_type'], unique=False)
    op.create_index(op.f('ix_printer_filament_profile_printer_model'), 'printer_filament_profile', ['printer_model'], unique=False)
    op.drop_index(op.f('ix_filament_settings_filament_type'), table_name='filament_settings')
    op.drop_index(op.f('ix_filament_settings_printer_model'), table_name='filament_settings')
    op.drop_table('filament_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filament_settings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('printer_model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('printer_nozzle_diameter', sa.FLOAT(), nullable=False),
    sa.Column('filament_brand', sa.VARCHAR(length=100), nullable=False),
    sa.Column('filament_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('filament_diameter', sa.FLOAT(), nullable=False),
    sa.Column('chamber_temp', sa.INTEGER(), nullable=False),
    sa.Column('nozzle_temp_first_layer', sa.INTEGER(), nullable=False),
    sa.Column('nozzle_temp_other_layers', sa.INTEGER(), nullable=False),
    sa.Column('bed_temp_first_layer', sa.INTEGER(), nullable=False),
    sa.Column('bed_temp_other_layers', sa.INTEGER(), nullable=False),
    sa.Column('bed_temp_initial', sa.INTEGER(), nullable=False),
    sa.Column('bed_temp_final', sa.INTEGER(), nullable=False),
    sa.Column('fan_min_speed', sa.INTEGER(), nullable=False),
    sa.Column('fan_min_layer_time', sa.INTEGER(), nullable=False),
    sa.Column('fan_max_speed', sa.INTEGER(), nullable=False),
    sa.Column('fan_max_layer_time', sa.INTEGER(), nullable=False),
    sa.Column('fan_always_on', sa.BOOLEAN(), nullable=False),
    sa.Column('slow_down_for_cooling', sa.BOOLEAN(), nullable=False),
    sa.Column('retraction_distance', sa.FLOAT(), nullable=False),
    sa.Column('retraction_speed', sa.FLOAT(), nullable=False),
    sa.Column('print_speed_first_layer', sa.FLOAT(), nullable=False),
    sa.Column('print_speed_other_layers', sa.FLOAT(), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('min_layer_area', sa.FLOAT(), nullable=False),
    sa.Column('max_overhang_angle', sa.FLOAT(), nullable=True),
    sa.Column('has_bridges', sa.BOOLEAN(), nullable=False),
    sa.Column('min_wall_thickness', sa.FLOAT(), nullable=True),
    sa.Column('max_height', sa.FLOAT(), nullable=False),
    sa.Column('bounding_box_volume', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filament_settings_printer_model'), 'filament_settings', ['printer_model'], unique=False)
    op.create_index(op.f('ix_filament_settings_filament_type'), 'filament_settings', ['filament_type'], unique=False)
    op.drop_index(op.f('ix_printer_filament_profile_printer_model'), table_name='printer_filament_profile')
    op.drop_index(op.f('ix_printer_filament_profile_filament_type'), table_name='printer_filament_profile')
    op.drop_table('printer_filament_profile')
    op.drop_table('geometry_settings')
    # ### end Alembic commands ###
