"""additional settings based on stl

Revision ID: c7575b2f4024
Revises: 30cf64d7030a
Create Date: 2026-05-28 15:11:55.858666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7575b2f4024'
down_revision: Union[str, Sequence[str], None] = '30cf64d7030a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament_settings', sa.Column('min_layer_area', sa.Float(), nullable=False, comment='Минимальная площадь слоя (мм²), для расчёта time-lapse обдува'))
    op.add_column('filament_settings', sa.Column('max_overhang_angle', sa.Float(), nullable=True, comment='Максимальный угол свеса в градусах'))
    op.add_column('filament_settings', sa.Column('has_bridges', sa.Boolean(), nullable=False, comment='Есть ли мосты'))
    op.add_column('filament_settings', sa.Column('min_wall_thickness', sa.Float(), nullable=True, comment='Минимальная толщина стенки (мм)'))
    op.add_column('filament_settings', sa.Column('max_height', sa.Float(), nullable=False, comment='Общая высота модели (мм), для расчёта времени печати'))
    op.add_column('filament_settings', sa.Column('bounding_box_volume', sa.Float(), nullable=False, comment='Объём ограничивающего параллелепипеда (мм³)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filament_settings', 'bounding_box_volume')
    op.drop_column('filament_settings', 'max_height')
    op.drop_column('filament_settings', 'min_wall_thickness')
    op.drop_column('filament_settings', 'has_bridges')
    op.drop_column('filament_settings', 'max_overhang_angle')
    op.drop_column('filament_settings', 'min_layer_area')
    # ### end Alembic commands ###
