"""delete model name from geometry_settings

Revision ID: e07c108e4ca8
Revises: 9bdbff72a108
Create Date: 2026-05-28 15:32:06.156235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07c108e4ca8'
down_revision: Union[str, Sequence[str], None] = '9bdbff72a108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geometry_settings', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometry_settings', sa.Column('model_name', sa.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
